apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: vaultwarden
      repoURL: https://guerzon.github.io/vaultwarden
      targetRevision: 0.22.5
      helm:
        valueFiles:
          - $values/kubernetes/argocd/clusters/addons/apps/vaultwarden/values.yaml
    - path: kubernetes/argocd/clusters/addons/apps/vaultwarden
      repoURL: git@github.com:saulbel/stargate-homelab.git
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false