version: '3.9'
services:
  mariadb:
    image: mariadb
    restart: always
    env_file: .mariadb.env
    environment:
    # included in .env file
    # - MYSQL_RANDOM_ROOT_PASSWORD=
    # - MYSQL_DATABASE=teamspeak=
    # - MYSQL_USER=teamspeak=
    # - MYSQL_PASSWORD=
    volumes:
      - "/srv/teamspeak3/mariadb:/var/lib/mysql"

  teamspeak3:
    image: teamspeak
    container_name: teamspeak
    restart: always
    env_file: .teamspeak3.env
    environment:
      - "TS3SERVER_DB_PLUGIN=ts3db_mariadb"
      - "TS3SERVER_DB_SQLCREATEPATH=create_mariadb"
      - "TS3SERVER_DB_HOST=mariadb"
      - "TS3SERVER_DB_WAITUNTILREADY=30"
      - "TS3SERVER_LICENSE=accept"
      # included in .env file
      # - "TS3SERVER_DB_USER="
      # - "TS3SERVER_DB_PASSWORD="
      # - "TS3SERVER_DB_NAME="
    volumes:
      - "/srv/teamspeak3/data:/var/ts3server/"
    ports:
      - '9987:9987/udp'  # voice
      - '30033:30033'    # filetransfer
      - '10011:10011'
        #sinusbot:
        #image: sinusbot/docker
        #restart: always
        #ports:
        #- "[::1]:8000:8087"
        #volumes:
        #- "/srv/sinusbot/scripts:/opt/sinusbot/scripts"
        #- "/srv/sinusbot/data:/opt/sinusbot/data"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    env_file: .env
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NO_RESTART=false
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=teamspeak
      - WATCHTOWER_SCHEDULE=0 0 12 * * 0
      # included in .env file
      # - WATCHTOWER_NOTIFICATION_URL=