apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: external-dns
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 6.36.1
      helm:
        valueFiles:
          - $values/kubernetes/argocd/clusters/addons/software-base/external-dns/values.yaml
    - path: clusters/addons/software-base/external-dns
      repoURL: git@github.com:saulbel/stargate-homelab.git
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true