apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.18.0
      helm:
        valueFiles:
          - $values/kubernetes/argocd/clusters/addons/software-base/external-secrets/values.yaml
    - path: kubernetes/argocd/clusters/addons/software-base/external-secrets
      repoURL: git@github.com:saulbel/stargate-homelab.git
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true