apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    namespace: longhorn
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.6.1
      helm:
        valueFiles:
          - $values/kubernetes/argocd/clusters/addons/software-base/longhorn/values.yaml
    - path: kubernetes/argocd/clusters/addons/software-base/longhorn
      repoURL: git@github.com:saulbel/stargate-homelab.git
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true