apiVersion: v1
kind: Secret
metadata: 
  name: docker-registry
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:  
  url: registry-1.docker.io
  username: "docker"
  password: ""
  name: docker-registry
  enableOCI: "true"
  type: "helm"
