apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-global
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_OAUTH_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_OAUTH_CLIENT_SECRET