apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-minio-credentials
  namespace: longhorn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-global
    kind: ClusterSecretStore
  target:
    name: longhorn-minio-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: AWS_ENDPOINTS