provider: webhook

extraArgs:
  webhook-provider-url: http://localhost:8888

sidecars:
  - name: adguard-webhook
    image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.0
    imagePullPolicy: IfNotPresent
    ports:
      - name: http
        containerPort: 8888
    env:
      - name: LOG_LEVEL
        value: debug
      - name: ADGUARD_URL
        valueFrom:
          secretKeyRef:
            name: adguard-webhook-secret
            key: adguard-url
      - name: ADGUARD_USER
        valueFrom:
          secretKeyRef:
            name: adguard-webhook-secret
            key: adguard-user
      - name: ADGUARD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: adguard-webhook-secret
            key: adguard-password
      - name: SERVER_HOST
        value: 0.0.0.0
      - name: DRY_RUN
        value: "false"