apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-global
    kind: ClusterSecretStore
  target:
    name: vaultwarden-admin-token
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: VAULTWARDEN_ADMIN_TOKEN