apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-global
spec:
  provider:
    infisical:
      hostAPI: http://infisical.home:80
      auth:
        universalAuthCredentials:
          clientId:
            name: universal-auth-credentials
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: universal-auth-credentials
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        projectSlug: k3s-f-nf-k
        environmentSlug: dev
        secretsPath: /
        recursive: false