apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-global
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: cloud
      remoteRef:
        key: AWS_CREDENTIALS_FILE