version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    env_file: .vaultwarden.env
    environment:
      # included in .env file
      # - SIGNUPS_ALLOWED=
      # - INVITATIONS_ALLOWED=
      # - DOMAIN=
      # - ADMIN_TOKEN=
    volumes:
        - ./vaultwarden:/data/
    ports:
        - 80:80
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    env_file: .env
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NO_RESTART=false
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=vaultwarden
      - WATCHTOWER_SCHEDULE=0 0 12 * * 0
      # included in .env file
      # - WATCHTOWER_NOTIFICATION_URL=